config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    collection do
      get 'top'
      get 'worst'
    end
    member do
      get 'chef'
      get 'address'
      # restaurants/33/address
    end
    resources :reviews, shallow: true
    namespace :admin do
      resources :restaurants, only: [:index]
    end
  end

end



# get 'restaurants/top', to: "restaurants#top", as: :top_restaurants

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # has_many or has_one
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :stars, inclusion: { in: (1..5)}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, length: {minimum: 20}

end

app/controllers/admin/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = current_user.restaurants
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end


  def top
    @top_restaurants = Restaurant.where(stars: 5)
  end

  def worst
    @worst_restaurants = Restaurant.where(stars: 1)
  end

  # GET /restaurants/1
  def show
  end

  def chef
    # @restaurant = Restaurant.find(params[:id])
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :description, :stars)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant_id = @restaurant.id
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address  %>
    <%= f.input :description %>
    <%= f.input :stars %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>description</th>
      <th>chef</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% restos.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %>
          <td><%= restaurant.description %></td>
          <td><%= restaurant.chef %> </td>
          <td><%= restaurant.stars %></td>
          <td><%= link_to 'Show', restaurant %></td>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/restaurants/chef.html.erb
<h1>The chef of <%= @restaurant.name %> is <%= @restaurant.chef %></h1>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Restaurants</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Addressdescription</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %>
          <td><%= restaurant.description %>
            <td><%= restaurant.stars %></td>
            <td><%= link_to 'Show', restaurant %></td>
            <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
            <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>
<p>
  <strong>Stars:</strong>
  <%= @restaurant.stars %>
</p>
<h4>Reviews</h4>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %></li>
  <% end %>
</ul>
<%= link_to "Add a review" , new_restaurant_review_path(@restaurant)  %>
| <%= link_to "More about the chef", chef_restaurant_path(@restaurant)  %>
| <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/top.html.erb
<p id="notice"><%= notice %></p>
<h1>Best Restaurants</h1>
<%= render 'list', restos: @top_restaurants %>
<br>
<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/worst.html.erb
<p id="notice"><%= notice %></p>
<h1>Worst Restaurants</h1>
<!-- partial with locals (local variables) -->
<%= render 'list', restos: @worst_restaurants %>
<br>
<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<!-- localhost:3000/restaurants/42/reviews -->
<form action="/restaurants/42/reviews" method="post">
</form>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>